name: Build Sphinx Documentation and check links

on:
  schedule:
    # Weekly, at 03:00 on Monday UTC
    - cron: "0 3 * * 1"
  pull_request:
    paths:
      - ".github/workflows/sphinx.yml"

      - "docs/**"
      - "README.md"
      - "CHANGELOG.md"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/sphinx.yml"

      - "docs/**"
      - "README.md"
      - "CHANGELOG.md"
  workflow_dispatch:

jobs:
  build-docs:
    permissions:
      contents: write
    if: github.repository_owner == 'jupyter' || github.repository_owner == 'mathbunnyru' || github.event_name != 'schedule'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install uv 📦
        uses: astral-sh/setup-uv@v7

      - name: Install Doc Dependencies 📦
        run: uv sync --frozen
        shell: bash

      - name: Build Documentation 📖
        run: make docs

      - name: Check Documentation URLs 🔗
        run: make linkcheck-docs || make linkcheck-docs
